javac -d . Fonction.java
javac -d . Bienvenue.java
javac -d . Contentpane.java
javac -d . Fenetre.java
javac -d . FenetreListener.java
javac -d . Champ.java
javac -d . Bouton.java
javac -d . Configuration.java
javac -d . Displayphoto.java
javac -d . GIFdisplayer.java
javac -d . Accueil.java
javac -d . Fichier.java
javac -d . ArtistTitle.java
javac -d . InfoMusic.java
javac -d . Picture.java
javac -d . Music.java
javac -d . Video.java
javac -d . Menu.java