javac -d . Function.java
javac -d . MusicPlayer.java
javac -d . BytePacket.java
javac -d . FichierPack.java
javac -d . FirstPacket.java
javac -d . FirstResponse.java
javac -d . SecondPacket.java
javac -d . Metadata.java
javac -d . MusicVideoPack.java
javac -d . Myclient.java
javac -d . Myserver.java
javac -d . ClientProcess.java
javac -d . StartServer.java